# 随机数生成

In [1]:
import numpy as np

### 随机种子seed

seed( ) 用于指定随机数生成时所用算法开始的整数值。   
1.如果使用相同的seed( )值，则每次生成的随即数都相同     
2.如果不设置这个值，则系统根据时间来自己选择这个值，此时每次生成的随机数因时间差异而不同     
3.设置的seed()值仅一次有效

In [2]:
num=0
while(num<3):
    np.random.seed(3)
    print(np.random.random())
    num+=1

0.5507979025745755
0.5507979025745755
0.5507979025745755


In [3]:
num=0
np.random.seed(3)
while(num<3):
    print(np.random.random())
    num+=1

0.5507979025745755
0.7081478226181048
0.2909047389129443


### normal: 正太（高斯）分布

In [4]:
np.random.normal(size=(2,2))

array([[ 0.98055387,  0.02701904],
       [-0.46004212, -0.05792084]])

### permutation: 返回一个序列的随机排列，或返回一个随机排列范围

permutation返回的是随机排列后的副本，而shuffle是对数据直接进行洗牌（无返回值）

In [5]:
np.random.permutation([1, 4, 9, 12, 15])

array([12, 15,  4,  9,  1])

In [6]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [7]:
np.random.permutation(10)

array([4, 7, 8, 6, 0, 5, 9, 3, 1, 2])

### shuffle: 对一个序列就地随机排列

In [8]:
arr_shuffle = np.arange(9).reshape((3, 3))
return_result = np.random.shuffle(arr_shuffle)
print (return_result)

None


In [9]:
arr_shuffle

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### rand: 产生均匀分布的样本值

均匀分布在[0, 1)

In [10]:
np.random.rand(2, 3)

array([[0.58661997, 0.27492011, 0.45460777],
       [0.75766525, 0.81757073, 0.25758529]])

### randint:从给定的上下限范围内随机选取整数

In [11]:
np.random.randint(2,5,size=8)

array([3, 3, 4, 2, 2, 4, 2, 2])

### randn:产生正态分布（平均值为0，标准差为1）的样本值

In [12]:
np.random.randn(3,2)

array([[-0.40791451,  1.24757841],
       [-1.82938368, -1.59651767],
       [ 0.69031204,  0.92812246]])

### uniform: 产生在[0,1)中均匀分布的样本值

In [13]:
np.random.uniform()

0.023117566295374203

### RandomState:创建一个随机的数据集

In [14]:
from numpy.random import RandomState
rdm= RandomState(1)
dataset_size = 5
x = rdm.rand(dataset_size,2)  #创建rand的随机数集,数据规模为 dataset_size × 2
x

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])