# 随机数生成

In [1]:
import numpy as np

### 随机种子seed

seed( ) 用于指定随机数生成时所用算法开始的整数值。   
1.如果使用相同的seed( )值，则每次生成的随即数都相同     
2.如果不设置这个值，则系统根据时间来自己选择这个值，此时每次生成的随机数因时间差异而不同     
3.设置的seed()值仅一次有效

In [23]:
num=0
while(num<3):
    np.random.seed(3)
    print(random.random())
    num+=1

0.5507979025745755
0.5507979025745755
0.5507979025745755


In [24]:
num=0
np.random.seed(3)
while(num<3):
    print(random.random())
    num+=1

0.5507979025745755
0.7081478226181048
0.2909047389129443


### normal: 正太（高斯）分布

In [2]:
np.random.normal(size=(2,2))

array([[-1.39327236,  0.86881628],
       [ 0.58256885, -0.76409811]])

### permutation: 返回一个序列的随机排列，或返回一个随机排列范围

permutation返回的是随机排列后的副本，而shuffle是对数据直接进行洗牌（无返回值）

In [3]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 9,  1, 15, 12,  4])

In [4]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [5]:
np.random.permutation(10)

array([6, 7, 1, 2, 9, 5, 8, 3, 4, 0])

### shuffle: 对一个序列就地随机排列

In [6]:
arr_shuffle = np.arange(9).reshape((3, 3))
return_result = np.random.shuffle(arr_shuffle)
print (return_result)

None


In [7]:
arr_shuffle

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

### rand: 产生均匀分布的样本值

均匀分布在[0, 1)

In [9]:
np.random.rand(2, 3)

array([[0.33726303, 0.66283813, 0.72284131],
       [0.33156258, 0.89292222, 0.40090699]])

### randint:从给定的上下限范围内随机选取整数

In [17]:
np.random.randint(2,5,size=8)

array([3, 2, 4, 3, 2, 2, 2, 4])

### randn:产生正态分布（平均值为0，标准差为1）的样本值

In [19]:
np.random.randn(3,2)

array([[-0.87643341,  1.64965491],
       [-0.8784587 , -1.0985283 ],
       [-0.47693103, -0.82547055]])

### uniform: 产生在[0,1)中均匀分布的样本值

In [22]:
np.random.uniform()

0.8301876921390616